/**
 * Update best solutions with better comments and explanations
 * ONLY updates bestSolution field for questions 16-33
 * Does NOT touch questions 1-15 or any other data
 * 
 * Run: npx ts-node --compiler-options '{"module":"CommonJS"}' prisma/update-solutions.ts
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🚀 Updating solutions with better comments & explanations...");
  console.log("⚠️  Only updating questions 16-33. Questions 1-15 untouched.\n");

  let updated = 0;
  for (const [title, solution] of Object.entries(SOLUTIONS)) {
    const exercise = await prisma.exercise.findFirst({
      where: { title, lesson: { title: "Coding Practice Problems" } },
    });
    if (!exercise) { console.log(`  ⚠️  Not found: ${title}`); continue; }

    await prisma.exercise.update({
      where: { id: exercise.id },
      data: { bestSolution: solution as any },
    });
    updated++;
    console.log(`  ✅ [${updated}] ${title}`);
  }
  console.log(`\n🎉 Done! Updated: ${updated}`);
}

const SOLUTIONS: Record<string, any> = {
  "Factorial": {
    c: { code: "#include<stdio.h>\nint main(){\n    int n;\n    scanf(\"%d\",&n);\n    long long factorial = 1; // Initialize result\n    // Multiply from 2 to n\n    for(int i = 2; i <= n; i++)\n        factorial *= i;\n    printf(\"%lld\", factorial);\n    return 0;\n}", timeComplexity: "O(n)", spaceComplexity: "O(1)", explanation: "We multiply all numbers from 1 to N iteratively. For N=0, factorial is 1 by definition. We use long long to handle large values up to 20!." },
    java: { code: "import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        int n = new Scanner(System.in).nextInt();\n        long factorial = 1; // Initialize result\n        // Multiply from 2 to n\n        for(int i = 2; i <= n; i++)\n            factorial *= i;\n        System.out.println(factorial);\n    }\n}", timeComplexity: "O(n)", spaceComplexity: "O(1)", explanation: "Iterative multiplication from 1 to N. Uses long to handle large factorials." },
    python: { code: "n = int(input())\nresult = 1  # Initialize factorial\n# Multiply from 2 to n\nfor i in range(2, n+1):\n    result *= i\nprint(result)", timeComplexity: "O(n)", spaceComplexity: "O(1)", explanation: "Simple loop multiplying all numbers from 2 to N. Python handles big numbers natively." },
    javascript: { code: "const n = parseInt(require('fs').readFileSync('/dev/stdin','utf8').trim());\nlet factorial = 1; // Initialize result\n// Multiply from 2 to n\nfor(let i = 2; i <= n; i++)\n    factorial *= i;\nconsole.log(factorial);", timeComplexity: "O(n)", spaceComplexity: "O(1)", explanation: "Iterative approach — multiply all numbers from 2 to N." }
  },
  "Fibonacci Nth Term": {
    c: { code: "#include<stdio.h>\nint main(){\n    int n;\n    scanf(\"%d\",&n);\n    if(n <= 1){ printf(\"%d\",n); return 0; }\n    int prev = 0, curr = 1; // F(0)=0, F(1)=1\n    // Build up to F(n)\n    for(int i = 2; i <= n; i++){\n        int next = prev + curr; // F(i) = F(i-1) + F(i-2)\n        prev = curr;\n        curr = next;\n    }\n    printf(\"%d\", curr);\n    return 0;\n}", timeComplexity: "O(n)", spaceComplexity: "O(1)", explanation: "We use two variables to track previous two Fibonacci numbers and iterate up to N. This avoids recursion overhead and uses constant space." },
    java: { code: "import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        int n = new Scanner(System.in).nextInt();\n        if(n <= 1){ System.out.println(n); return; }\n        int prev = 0, curr = 1; // F(0)=0, F(1)=1\n        // Build up to F(n)\n        for(int i = 2; i <= n; i++){\n            int next = prev + curr;\n            prev = curr;\n            curr = next;\n        }\n        System.out.println(curr);\n    }\n}", timeComplexity: "O(n)", spaceComplexity: "O(1)", explanation: "Iterative approach using two variables. Much faster than recursive approach which would be O(2^n)." },
    python: { code: "n = int(input())\nif n <= 1:\n    print(n)\nelse:\n    prev, curr = 0, 1  # F(0)=0, F(1)=1\n    # Build up to F(n)\n    for _ in range(2, n+1):\n        prev, curr = curr, prev + curr\n    print(curr)", timeComplexity: "O(n)", spaceComplexity: "O(1)", explanation: "Python's tuple swap makes this clean. We iterate from F(2) to F(n) using just two variables." },
    javascript: { code: "const n = parseInt(require('fs').readFileSync('/dev/stdin','utf8').trim());\nif(n <= 1){ console.log(n); }\nelse{\n    let prev = 0, curr = 1; // F(0)=0, F(1)=1\n    // Build up to F(n)\n    for(let i = 2; i <= n; i++)\n        [prev, curr] = [curr, prev + curr];\n    console.log(curr);\n}", timeComplexity: "O(n)", spaceComplexity: "O(1)", explanation: "Iterative with destructuring swap. Efficient O(n) time with O(1) space." }
  },
  "Prime Check": {
    c: { code: "#include<stdio.h>\nint main(){\n    int n;\n    scanf(\"%d\",&n);\n    if(n < 2){ printf(\"No\"); return 0; } // 0,1 are not prime\n    // Check divisibility from 2 to sqrt(n)\n    for(int i = 2; i * i <= n; i++){\n        if(n % i == 0){\n            printf(\"No\"); return 0; // Found a divisor\n        }\n    }\n    printf(\"Yes\"); // No divisors found — prime!\n    return 0;\n}", timeComplexity: "O(sqrt(n))", spaceComplexity: "O(1)", explanation: "A number is prime if it has no divisors other than 1 and itself. We only need to check up to sqrt(n) because if n = a*b, one of them must be <= sqrt(n)." },
    java: { code: "import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        int n = new Scanner(System.in).nextInt();\n        if(n < 2){ System.out.println(\"No\"); return; }\n        // Check divisibility from 2 to sqrt(n)\n        for(int i = 2; i * i <= n; i++){\n            if(n % i == 0){\n                System.out.println(\"No\"); return;\n            }\n        }\n        System.out.println(\"Yes\");\n    }\n}", timeComplexity: "O(sqrt(n))", spaceComplexity: "O(1)", explanation: "Check divisors up to sqrt(n). If any divides n evenly, it's not prime. This is much faster than checking all numbers up to n." },
    python: { code: "n = int(input())\nif n < 2:\n    print('No')  # 0, 1 are not prime\nelse:\n    is_prime = True\n    i = 2\n    # Check divisors up to sqrt(n)\n    while i * i <= n:\n        if n % i == 0:\n            is_prime = False\n            break\n        i += 1\n    print('Yes' if is_prime else 'No')", timeComplexity: "O(sqrt(n))", spaceComplexity: "O(1)", explanation: "We check if any number from 2 to sqrt(n) divides n. If none does, n is prime. The sqrt optimization reduces checks significantly." },
    javascript: { code: "const n = parseInt(require('fs').readFileSync('/dev/stdin','utf8').trim());\nif(n < 2){ console.log('No'); }\nelse{\n    let isPrime = true;\n    // Check divisors up to sqrt(n)\n    for(let i = 2; i * i <= n; i++){\n        if(n % i === 0){ isPrime = false; break; }\n    }\n    console.log(isPrime ? 'Yes' : 'No');\n}", timeComplexity: "O(sqrt(n))", spaceComplexity: "O(1)", explanation: "Only check divisibility up to sqrt(n). This gives us O(sqrt(n)) time instead of O(n)." }
  },
  "GCD of Two Numbers": {
    c: { code: "#include<stdio.h>\n// Euclidean algorithm: GCD(a,b) = GCD(b, a%b)\nint gcd(int a, int b){\n    return b == 0 ? a : gcd(b, a % b);\n}\nint main(){\n    int a, b;\n    scanf(\"%d%d\", &a, &b);\n    printf(\"%d\", gcd(a, b));\n    return 0;\n}", timeComplexity: "O(log(min(a,b)))", spaceComplexity: "O(log(min(a,b)))", explanation: "Euclidean algorithm: repeatedly replace (a,b) with (b, a%b) until b becomes 0. The remaining a is the GCD. Very efficient — logarithmic time." },
    java: { code: "import java.util.*;\npublic class Main {\n    // Euclidean algorithm\n    static int gcd(int a, int b){\n        return b == 0 ? a : gcd(b, a % b);\n    }\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        System.out.println(gcd(sc.nextInt(), sc.nextInt()));\n    }\n}", timeComplexity: "O(log(min(a,b)))", spaceComplexity: "O(log(min(a,b)))", explanation: "Euclidean algorithm recursively finds GCD by replacing larger number with remainder. GCD(12,8) → GCD(8,4) → GCD(4,0) = 4." },
    python: { code: "a, b = map(int, input().split())\n# Euclidean algorithm\nwhile b:\n    a, b = b, a % b  # Replace (a,b) with (b, a%b)\nprint(a)  # When b=0, a is the GCD", timeComplexity: "O(log(min(a,b)))", spaceComplexity: "O(1)", explanation: "Iterative Euclidean algorithm. Keep replacing a,b with b,a%b until b becomes 0. The answer is a. Very fast even for large numbers." },
    javascript: { code: "const [a, b] = require('fs').readFileSync('/dev/stdin','utf8').trim().split(' ').map(Number);\n// Euclidean algorithm\nfunction gcd(a, b){\n    return b === 0 ? a : gcd(b, a % b);\n}\nconsole.log(gcd(a, b));", timeComplexity: "O(log(min(a,b)))", spaceComplexity: "O(log(min(a,b)))", explanation: "Recursive Euclidean algorithm. GCD(a,b) = GCD(b, a%b). Base case: GCD(a,0) = a." }
  },
  "Power of Two": {
    c: { code: "#include<stdio.h>\nint main(){\n    int n;\n    scanf(\"%d\", &n);\n    // Bit trick: power of 2 has exactly one bit set\n    // n & (n-1) removes the lowest set bit\n    // If result is 0, only one bit was set = power of 2\n    printf(n > 0 && (n & (n-1)) == 0 ? \"Yes\" : \"No\");\n    return 0;\n}", timeComplexity: "O(1)", spaceComplexity: "O(1)", explanation: "Bit manipulation trick: A power of 2 in binary has exactly one '1' bit (like 1000). n & (n-1) removes the lowest set bit. If result is 0 and n > 0, it's a power of 2." },
    java: { code: "import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        int n = new Scanner(System.in).nextInt();\n        // Bit trick: power of 2 has one bit set\n        // n & (n-1) clears lowest set bit\n        System.out.println(n > 0 && (n & (n-1)) == 0 ? \"Yes\" : \"No\");\n    }\n}", timeComplexity: "O(1)", spaceComplexity: "O(1)", explanation: "Uses bit manipulation. Powers of 2 have exactly one bit set in binary. n & (n-1) removes that bit — if result is 0, it was a power of 2." },
    python: { code: "n = int(input())\n# Bit trick: power of 2 has exactly one '1' bit\n# n & (n-1) removes the lowest set bit\n# If result is 0 and n > 0, it's a power of 2\nprint('Yes' if n > 0 and (n & (n-1)) == 0 else 'No')", timeComplexity: "O(1)", spaceComplexity: "O(1)", explanation: "Bit trick: In binary, powers of 2 look like 1, 10, 100, 1000. Using n & (n-1) == 0 checks this in O(1) time." },
    javascript: { code: "const n = parseInt(require('fs').readFileSync('/dev/stdin','utf8').trim());\n// Bit trick: power of 2 has exactly one bit set\n// n & (n-1) clears the lowest set bit\nconsole.log(n > 0 && (n & (n-1)) === 0 ? 'Yes' : 'No');", timeComplexity: "O(1)", spaceComplexity: "O(1)", explanation: "O(1) bit manipulation. Powers of 2 have single bit set. n & (n-1) removes it — if 0, it's a power of 2." }
  },
  "Bubble Sort": {
    c: { code: "#include<stdio.h>\nint main(){\n    int n;\n    scanf(\"%d\", &n);\n    int arr[n];\n    for(int i = 0; i < n; i++) scanf(\"%d\", &arr[i]);\n    // Bubble sort: compare adjacent, swap if needed\n    for(int i = 0; i < n-1; i++)\n        for(int j = 0; j < n-i-1; j++)\n            if(arr[j] > arr[j+1]){\n                int temp = arr[j];\n                arr[j] = arr[j+1];\n                arr[j+1] = temp;\n            }\n    // Print sorted array\n    for(int i = 0; i < n; i++)\n        printf(\"%d%s\", arr[i], i < n-1 ? \" \" : \"\");\n    return 0;\n}", timeComplexity: "O(n²)", spaceComplexity: "O(1)", explanation: "Bubble sort repeatedly compares adjacent elements and swaps them if in wrong order. After each pass, the largest unsorted element 'bubbles' to its correct position." },
    java: { code: "import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for(int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        // Use built-in sort (efficient)\n        Arrays.sort(arr);\n        // Print result\n        StringBuilder sb = new StringBuilder();\n        for(int i = 0; i < n; i++)\n            sb.append(arr[i]).append(i < n-1 ? \" \" : \"\");\n        System.out.println(sb);\n    }\n}", timeComplexity: "O(n log n)", spaceComplexity: "O(1)", explanation: "Using Arrays.sort() which implements dual-pivot quicksort — much faster than bubble sort for large arrays." },
    python: { code: "n = int(input())\narr = list(map(int, input().split()))\n# Python's built-in sort (Timsort - very efficient)\narr.sort()\nprint(' '.join(map(str, arr)))", timeComplexity: "O(n log n)", spaceComplexity: "O(n)", explanation: "Python's built-in sort uses Timsort algorithm which is O(n log n) in average case. Much better than O(n²) bubble sort." },
    javascript: { code: "const lines = require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\nconst arr = lines[1].split(' ').map(Number);\n// Sort numerically (not lexicographically)\narr.sort((a, b) => a - b);\nconsole.log(arr.join(' '));", timeComplexity: "O(n log n)", spaceComplexity: "O(1)", explanation: "JavaScript's sort with numeric comparator. Without (a,b)=>a-b, it sorts lexicographically which gives wrong results for numbers." }
  },
  "Sort Even and Odd": {
    c: { code: "#include<stdio.h>\n#include<stdlib.h>\nint cmp(const void*a, const void*b){ return *(int*)a - *(int*)b; }\nint main(){\n    int n;\n    scanf(\"%d\", &n);\n    int arr[n], evens[n], odds[n], ec=0, oc=0;\n    for(int i = 0; i < n; i++){\n        scanf(\"%d\", &arr[i]);\n        // Separate into evens and odds\n        if(arr[i] % 2 == 0) evens[ec++] = arr[i];\n        else odds[oc++] = arr[i];\n    }\n    // Sort each group\n    qsort(evens, ec, sizeof(int), cmp);\n    qsort(odds, oc, sizeof(int), cmp);\n    // Print evens first, then odds\n    for(int i = 0; i < ec; i++) printf(\"%d \", evens[i]);\n    for(int i = 0; i < oc; i++) printf(\"%d%s\", odds[i], i<oc-1?\" \":\"\");\n    return 0;\n}", timeComplexity: "O(n log n)", spaceComplexity: "O(n)", explanation: "Separate numbers into even and odd groups, sort each group independently, then print evens followed by odds." },
    java: { code: "import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        // Separate into even and odd lists\n        List<Integer> evens = new ArrayList<>();\n        List<Integer> odds = new ArrayList<>();\n        for(int i = 0; i < n; i++){\n            int x = sc.nextInt();\n            if(x % 2 == 0) evens.add(x);\n            else odds.add(x);\n        }\n        // Sort each group\n        Collections.sort(evens);\n        Collections.sort(odds);\n        // Print evens first, then odds\n        StringBuilder sb = new StringBuilder();\n        for(int x : evens) sb.append(x).append(' ');\n        for(int x : odds) sb.append(x).append(' ');\n        System.out.println(sb.toString().trim());\n    }\n}", timeComplexity: "O(n log n)", spaceComplexity: "O(n)", explanation: "Use two ArrayLists to separate evens and odds, sort each, then concatenate for output." },
    python: { code: "n = int(input())\narr = list(map(int, input().split()))\n# Separate, sort each group\nevens = sorted(x for x in arr if x % 2 == 0)\nodds = sorted(x for x in arr if x % 2 != 0)\n# Print evens first, then odds\nprint(' '.join(map(str, evens + odds)))", timeComplexity: "O(n log n)", spaceComplexity: "O(n)", explanation: "List comprehension to filter evens/odds, sort each, then concatenate. Python makes this very concise." },
    javascript: { code: "const lines = require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\nconst arr = lines[1].split(' ').map(Number);\n// Separate and sort\nconst evens = arr.filter(x => x % 2 === 0).sort((a,b) => a-b);\nconst odds = arr.filter(x => x % 2 !== 0).sort((a,b) => a-b);\n// Evens first, then odds\nconsole.log([...evens, ...odds].join(' '));", timeComplexity: "O(n log n)", spaceComplexity: "O(n)", explanation: "Filter into two arrays, sort each numerically, then spread and join." }
  },
  "Binary Search": {
    c: { code: "#include<stdio.h>\nint main(){\n    int n, x;\n    scanf(\"%d%d\", &n, &x);\n    int arr[n];\n    for(int i = 0; i < n; i++) scanf(\"%d\", &arr[i]);\n    // Binary search\n    int lo = 0, hi = n-1, ans = -1;\n    while(lo <= hi){\n        int mid = (lo + hi) / 2;  // Middle element\n        if(arr[mid] == x){ ans = mid; break; }  // Found!\n        else if(arr[mid] < x) lo = mid + 1;  // Search right half\n        else hi = mid - 1;  // Search left half\n    }\n    printf(\"%d\", ans);\n    return 0;\n}", timeComplexity: "O(log n)", spaceComplexity: "O(1)", explanation: "Binary search works on sorted arrays. Compare target with middle element — if equal, found. If target is larger, search right half. If smaller, search left half. Each step eliminates half the array." },
    java: { code: "import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), x = sc.nextInt();\n        int[] arr = new int[n];\n        for(int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        // Binary search\n        int lo = 0, hi = n-1, ans = -1;\n        while(lo <= hi){\n            int mid = (lo + hi) / 2;\n            if(arr[mid] == x){ ans = mid; break; }\n            else if(arr[mid] < x) lo = mid + 1;\n            else hi = mid - 1;\n        }\n        System.out.println(ans);\n    }\n}", timeComplexity: "O(log n)", spaceComplexity: "O(1)", explanation: "Classic binary search — halve the search space at each step. O(log n) is much faster than linear search O(n) for large arrays." },
    python: { code: "n, x = map(int, input().split())\narr = list(map(int, input().split()))\n# Binary search\nlo, hi = 0, n-1\nans = -1\nwhile lo <= hi:\n    mid = (lo + hi) // 2  # Middle index\n    if arr[mid] == x:\n        ans = mid; break  # Found!\n    elif arr[mid] < x:\n        lo = mid + 1  # Search right\n    else:\n        hi = mid - 1  # Search left\nprint(ans)", timeComplexity: "O(log n)", spaceComplexity: "O(1)", explanation: "Binary search divides search space in half each iteration. For 1 million elements, we need at most 20 comparisons instead of 1 million." },
    javascript: { code: "const lines = require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\nconst [n, x] = lines[0].split(' ').map(Number);\nconst arr = lines[1].split(' ').map(Number);\n// Binary search\nlet lo = 0, hi = n-1, ans = -1;\nwhile(lo <= hi){\n    const mid = Math.floor((lo+hi)/2);\n    if(arr[mid] === x){ ans = mid; break; }\n    else if(arr[mid] < x) lo = mid+1;\n    else hi = mid-1;\n}\nconsole.log(ans);", timeComplexity: "O(log n)", spaceComplexity: "O(1)", explanation: "Binary search — O(log n) time. Use Math.floor for integer division of mid index." }
  },
  "Count Occurrences": {
    c: { code: "#include<stdio.h>\nint main(){\n    int n, x;\n    scanf(\"%d%d\", &n, &x);\n    int count = 0;\n    // Count how many times x appears\n    for(int i = 0; i < n; i++){\n        int num;\n        scanf(\"%d\", &num);\n        if(num == x) count++;  // Match found\n    }\n    printf(\"%d\", count);\n    return 0;\n}", timeComplexity: "O(n)", spaceComplexity: "O(1)", explanation: "Simple linear scan — read each element and increment counter whenever it matches the target. No extra space needed." },
    java: { code: "import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), x = sc.nextInt();\n        int count = 0;\n        // Count occurrences of x\n        for(int i = 0; i < n; i++)\n            if(sc.nextInt() == x) count++;\n        System.out.println(count);\n    }\n}", timeComplexity: "O(n)", spaceComplexity: "O(1)", explanation: "Read each number and compare with target. Simple O(n) scan with a counter variable." },
    python: { code: "n, x = map(int, input().split())\narr = list(map(int, input().split()))\n# Python's built-in count method\nprint(arr.count(x))", timeComplexity: "O(n)", spaceComplexity: "O(1)", explanation: "Python's list.count() method does exactly this — counts occurrences of a value in O(n) time." },
    javascript: { code: "const lines = require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\nconst [n, x] = lines[0].split(' ').map(Number);\nconst arr = lines[1].split(' ').map(Number);\n// Filter matching elements and count\nconsole.log(arr.filter(a => a === x).length);", timeComplexity: "O(n)", spaceComplexity: "O(n)", explanation: "Use filter to get all matching elements, then check length. Clean functional approach." }
  },
  "Sum of Digits": {
    c: { code: "#include<stdio.h>\n// Recursive: sum last digit + sum of remaining digits\nint sumDigits(int n){\n    if(n < 10) return n;  // Base case: single digit\n    return n % 10 + sumDigits(n / 10);  // Last digit + rest\n}\nint main(){\n    int n;\n    scanf(\"%d\", &n);\n    printf(\"%d\", sumDigits(n));\n    return 0;\n}", timeComplexity: "O(log n)", spaceComplexity: "O(log n)", explanation: "Recursively extract last digit (n%10) and add to sum of remaining digits (n/10). Base case: if n is single digit, return it directly. Recursion depth = number of digits." },
    java: { code: "import java.util.*;\npublic class Main {\n    // Recursive digit sum\n    static int sumDigits(int n){\n        if(n < 10) return n;  // Base case\n        return n % 10 + sumDigits(n / 10);  // Last digit + rest\n    }\n    public static void main(String[] args) {\n        System.out.println(sumDigits(new Scanner(System.in).nextInt()));\n    }\n}", timeComplexity: "O(log n)", spaceComplexity: "O(log n)", explanation: "Recursive approach: extract last digit with %10, get remaining number with /10, recurse until single digit. Stack depth equals number of digits in n." },
    python: { code: "def sum_digits(n):\n    if n < 10:  # Base case: single digit\n        return n\n    return n % 10 + sum_digits(n // 10)  # Last digit + rest\n\nprint(sum_digits(int(input())))", timeComplexity: "O(log n)", spaceComplexity: "O(log n)", explanation: "Recursive function: base case returns single digit, recursive case adds last digit (n%10) to sum_digits of remaining (n//10)." },
    javascript: { code: "const n = parseInt(require('fs').readFileSync('/dev/stdin','utf8').trim());\n// Recursive digit sum\nfunction sumDigits(n){\n    if(n < 10) return n;  // Base case\n    return n % 10 + sumDigits(Math.floor(n / 10));  // Last digit + rest\n}\nconsole.log(sumDigits(n));", timeComplexity: "O(log n)", spaceComplexity: "O(log n)", explanation: "Recursive: extract last digit, add to sum of rest. Use Math.floor for integer division." }
  },
  "Power (x^n)": {
    c: { code: "#include<stdio.h>\n// Fast power using divide and conquer\nlong long power(int x, int n){\n    if(n == 0) return 1;  // Base case: x^0 = 1\n    long long half = power(x, n/2);  // Compute x^(n/2)\n    if(n % 2 == 0)\n        return half * half;  // Even: x^n = (x^(n/2))^2\n    else\n        return half * half * x;  // Odd: x^n = (x^(n/2))^2 * x\n}\nint main(){\n    int x, n;\n    scanf(\"%d%d\", &x, &n);\n    printf(\"%lld\", power(x, n));\n    return 0;\n}", timeComplexity: "O(log n)", spaceComplexity: "O(log n)", explanation: "Fast exponentiation by squaring: instead of multiplying x n times, we split the problem in half each time. x^10 = (x^5)^2. This gives O(log n) time instead of O(n)." },
    java: { code: "import java.util.*;\npublic class Main {\n    // Fast power: divide and conquer\n    static long power(int x, int n){\n        if(n == 0) return 1;  // x^0 = 1\n        long half = power(x, n/2);\n        return n % 2 == 0 ? half * half : half * half * x;\n    }\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        System.out.println(power(sc.nextInt(), sc.nextInt()));\n    }\n}", timeComplexity: "O(log n)", spaceComplexity: "O(log n)", explanation: "Divide exponent by 2 at each step. Even exponent: square the half. Odd exponent: square the half and multiply by x once more." },
    python: { code: "x, n = map(int, input().split())\n\ndef power(x, n):\n    if n == 0: return 1  # Base case\n    half = power(x, n // 2)  # Solve half problem\n    if n % 2 == 0:\n        return half * half  # Even: square it\n    else:\n        return half * half * x  # Odd: square and multiply x\n\nprint(power(x, n))", timeComplexity: "O(log n)", spaceComplexity: "O(log n)", explanation: "Fast power by squaring. Reduces n multiplications to log(n) by splitting the exponent in half recursively." },
    javascript: { code: "const [x, n] = require('fs').readFileSync('/dev/stdin','utf8').trim().split(' ').map(Number);\n// Fast power: divide and conquer\nfunction power(x, n){\n    if(n === 0) return 1;  // Base case\n    const half = power(x, Math.floor(n/2));\n    return n % 2 === 0 ? half * half : half * half * x;\n}\nconsole.log(power(x, n));", timeComplexity: "O(log n)", spaceComplexity: "O(log n)", explanation: "Exponentiation by squaring — split exponent in half each call. Much faster than naive O(n) approach." }
  },
  "Print Linked List": {
    c: { code: "#include<stdio.h>\n#include<stdlib.h>\n// Node structure\nstruct Node {\n    int data;\n    struct Node* next;\n};\nint main(){\n    int n;\n    scanf(\"%d\", &n);\n    // Create and print linked list\n    struct Node* head = NULL;\n    struct Node* tail = NULL;\n    for(int i = 0; i < n; i++){\n        struct Node* node = (struct Node*)malloc(sizeof(struct Node));\n        scanf(\"%d\", &node->data);\n        node->next = NULL;\n        if(!head) head = node;\n        else tail->next = node;\n        tail = node;\n    }\n    // Traverse and print\n    struct Node* curr = head;\n    while(curr){\n        printf(\"%d%s\", curr->data, curr->next ? \" \" : \"\");\n        curr = curr->next;\n    }\n    return 0;\n}", timeComplexity: "O(n)", spaceComplexity: "O(n)", explanation: "Create a linked list by allocating nodes and linking them. Then traverse from head to NULL, printing each node's data. Uses tail pointer for O(1) insertion at end." },
    java: { code: "import java.util.*;\npublic class Main {\n    // Linked list node\n    static class Node {\n        int data;\n        Node next;\n        Node(int d){ data = d; next = null; }\n    }\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Node head = null, tail = null;\n        // Build linked list\n        for(int i = 0; i < n; i++){\n            Node node = new Node(sc.nextInt());\n            if(head == null) head = node;\n            else tail.next = node;\n            tail = node;\n        }\n        // Traverse and print\n        StringBuilder sb = new StringBuilder();\n        Node curr = head;\n        while(curr != null){\n            sb.append(curr.data);\n            if(curr.next != null) sb.append(' ');\n            curr = curr.next;\n        }\n        System.out.println(sb);\n    }\n}", timeComplexity: "O(n)", spaceComplexity: "O(n)", explanation: "Create Node objects, link them together, then traverse from head printing each value." },
    python: { code: "n = int(input())\narr = list(map(int, input().split()))\n# In Python, we can simulate with a list\n# Print elements in order (linked list traversal)\nprint(' '.join(map(str, arr)))", timeComplexity: "O(n)", spaceComplexity: "O(n)", explanation: "In Python, a list already provides sequential access. For this problem, reading and printing in order simulates linked list traversal." },
    javascript: { code: "const lines = require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\nconst arr = lines[1].split(' ');\n// Simulate linked list traversal by printing in order\nconsole.log(arr.join(' '));", timeComplexity: "O(n)", spaceComplexity: "O(n)", explanation: "Read elements and print in order — simulates creating a linked list and traversing it." }
  },
  "Valid Parentheses": {
    c: { code: "#include<stdio.h>\n#include<string.h>\nint main(){\n    char s[10001];\n    scanf(\"%s\", s);\n    char stack[10001]; // Use array as stack\n    int top = -1;\n    for(int i = 0; s[i]; i++){\n        // Push opening brackets\n        if(s[i]=='(' || s[i]=='[' || s[i]=='{')\n            stack[++top] = s[i];\n        else {\n            // Pop and check matching\n            if(top < 0){ printf(\"No\"); return 0; }\n            char c = stack[top--];\n            if((s[i]==')' && c!='(') ||\n               (s[i]==']' && c!='[') ||\n               (s[i]=='}' && c!='{')){\n                printf(\"No\"); return 0;\n            }\n        }\n    }\n    printf(top == -1 ? \"Yes\" : \"No\"); // Stack should be empty\n    return 0;\n}", timeComplexity: "O(n)", spaceComplexity: "O(n)", explanation: "Use a stack: push opening brackets, pop for closing brackets and check if they match. If stack is empty at end and all matched, it's valid." },
    java: { code: "import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        String s = new Scanner(System.in).next();\n        Stack<Character> stack = new Stack<>();\n        for(char c : s.toCharArray()){\n            // Push opening brackets\n            if(c=='(' || c=='[' || c=='{') stack.push(c);\n            else {\n                // Check matching closing bracket\n                if(stack.isEmpty()){ System.out.println(\"No\"); return; }\n                char top = stack.pop();\n                if((c==')' && top!='(') ||\n                   (c==']' && top!='[') ||\n                   (c=='}' && top!='{')){\n                    System.out.println(\"No\"); return;\n                }\n            }\n        }\n        System.out.println(stack.isEmpty() ? \"Yes\" : \"No\");\n    }\n}", timeComplexity: "O(n)", spaceComplexity: "O(n)", explanation: "Stack-based approach: opening brackets get pushed, closing brackets trigger pop and match check. Valid only if all match and stack is empty at end." },
    python: { code: "s = input()\nstack = []\nmatch = {')': '(', ']': '[', '}': '{'}\nvalid = True\nfor c in s:\n    if c in '([{':  # Opening bracket\n        stack.append(c)\n    else:  # Closing bracket\n        if not stack or stack[-1] != match[c]:\n            valid = False\n            break\n        stack.pop()  # Matched!\nprint('Yes' if valid and not stack else 'No')", timeComplexity: "O(n)", spaceComplexity: "O(n)", explanation: "Use list as stack. Map closing brackets to their opening counterparts. Push opens, pop and match closes. Valid if stack empty at end." },
    javascript: { code: "const s = require('fs').readFileSync('/dev/stdin','utf8').trim();\nconst stack = [];\nconst map = {')':'(', ']':'[', '}':'{'};\nlet valid = true;\nfor(const c of s){\n    if('([{'.includes(c)) stack.push(c);  // Push opens\n    else {\n        if(!stack.length || stack.pop() !== map[c]){ // Pop and match\n            valid = false; break;\n        }\n    }\n}\nconsole.log(valid && !stack.length ? 'Yes' : 'No');", timeComplexity: "O(n)", spaceComplexity: "O(n)", explanation: "Stack approach: push opening brackets, pop for closing and verify match using a lookup map." }
  },
  "Reverse String using Stack": {
    c: { code: "#include<stdio.h>\n#include<string.h>\nint main(){\n    char s[100001];\n    scanf(\"%s\", s);\n    int n = strlen(s);\n    // Use array index as stack — print from end\n    for(int i = n-1; i >= 0; i--)\n        printf(\"%c\", s[i]);\n    return 0;\n}", timeComplexity: "O(n)", spaceComplexity: "O(1)", explanation: "The array itself acts as a stack — printing from the last index to first reverses the string. Same concept as popping from a stack." },
    java: { code: "import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        String s = new Scanner(System.in).next();\n        // Push all characters to stack\n        Stack<Character> stack = new Stack<>();\n        for(char c : s.toCharArray()) stack.push(c);\n        // Pop all — gives reversed string\n        StringBuilder result = new StringBuilder();\n        while(!stack.isEmpty()) result.append(stack.pop());\n        System.out.println(result);\n    }\n}", timeComplexity: "O(n)", spaceComplexity: "O(n)", explanation: "Push all characters onto stack, then pop one by one. LIFO property of stack naturally reverses the order." },
    python: { code: "s = input()\n# Use list as stack\nstack = list(s)  # Push all chars\nresult = ''\nwhile stack:\n    result += stack.pop()  # Pop reverses order\nprint(result)", timeComplexity: "O(n)", spaceComplexity: "O(n)", explanation: "Use Python list as stack. Push all characters, then pop() gives them in reverse order (LIFO = Last In First Out)." },
    javascript: { code: "const s = require('fs').readFileSync('/dev/stdin','utf8').trim();\n// Use array as stack\nconst stack = [...s];  // Push all chars\nlet result = '';\nwhile(stack.length) result += stack.pop();  // Pop reverses\nconsole.log(result);", timeComplexity: "O(n)", spaceComplexity: "O(n)", explanation: "Spread string into array (push), then pop() gives reverse order. Stack's LIFO property does the reversal." }
  },
  "Sum of Binary Tree Nodes": {
    c: { code: "#include<stdio.h>\nint main(){\n    int n;\n    scanf(\"%d\", &n);\n    int sum = 0, x;\n    // Read each node value\n    for(int i = 0; i < n; i++){\n        scanf(\"%d\", &x);\n        if(x != -1) sum += x;  // Skip null nodes (-1)\n    }\n    printf(\"%d\", sum);\n    return 0;\n}", timeComplexity: "O(n)", spaceComplexity: "O(1)", explanation: "Simple traversal of level-order array. Add all values that are not -1 (null). No actual tree construction needed for this problem." },
    java: { code: "import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), sum = 0;\n        // Sum all non-null nodes\n        for(int i = 0; i < n; i++){\n            int x = sc.nextInt();\n            if(x != -1) sum += x;  // -1 means null\n        }\n        System.out.println(sum);\n    }\n}", timeComplexity: "O(n)", spaceComplexity: "O(1)", explanation: "Read level-order representation, sum all values except -1 (null nodes). Simple linear scan." },
    python: { code: "n = int(input())\nnodes = list(map(int, input().split()))\n# Sum all non-null nodes (-1 = null)\nprint(sum(x for x in nodes if x != -1))", timeComplexity: "O(n)", spaceComplexity: "O(1)", explanation: "Generator expression filters out -1 (null) values and sums the rest. No tree construction needed." },
    javascript: { code: "const lines = require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\nconst nodes = lines[1].split(' ').map(Number);\n// Sum all non-null nodes (filter out -1)\nconsole.log(nodes.filter(x => x !== -1).reduce((sum, x) => sum + x, 0));", timeComplexity: "O(n)", spaceComplexity: "O(n)", explanation: "Filter out -1 values (null nodes) and reduce to sum. Functional approach." }
  },
  "Climbing Stairs": {
    c: { code: "#include<stdio.h>\nint main(){\n    int n;\n    scanf(\"%d\", &n);\n    if(n <= 2){ printf(\"%d\", n); return 0; }\n    // DP: ways(n) = ways(n-1) + ways(n-2)\n    int prev = 1, curr = 2; // ways(1)=1, ways(2)=2\n    for(int i = 3; i <= n; i++){\n        int next = prev + curr;  // Current step's ways\n        prev = curr;\n        curr = next;\n    }\n    printf(\"%d\", curr);\n    return 0;\n}", timeComplexity: "O(n)", spaceComplexity: "O(1)", explanation: "Dynamic programming with Fibonacci pattern. To reach step n, you either came from step n-1 (1 step) or n-2 (2 steps). So ways(n) = ways(n-1) + ways(n-2). Use two variables instead of array." },
    java: { code: "import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        int n = new Scanner(System.in).nextInt();\n        if(n <= 2){ System.out.println(n); return; }\n        // Fibonacci-like DP\n        int prev = 1, curr = 2;\n        for(int i = 3; i <= n; i++){\n            int next = prev + curr;  // ways(i) = ways(i-1) + ways(i-2)\n            prev = curr;\n            curr = next;\n        }\n        System.out.println(curr);\n    }\n}", timeComplexity: "O(n)", spaceComplexity: "O(1)", explanation: "Same as Fibonacci sequence. ways(1)=1, ways(2)=2, ways(n)=ways(n-1)+ways(n-2). Use constant space with two variables." },
    python: { code: "n = int(input())\nif n <= 2:\n    print(n)\nelse:\n    # DP: ways(n) = ways(n-1) + ways(n-2)\n    prev, curr = 1, 2  # ways(1)=1, ways(2)=2\n    for _ in range(3, n+1):\n        prev, curr = curr, prev + curr\n    print(curr)", timeComplexity: "O(n)", spaceComplexity: "O(1)", explanation: "Fibonacci pattern: from step n, you came from n-1 or n-2. So total ways = ways(n-1) + ways(n-2). Constant space using tuple swap." },
    javascript: { code: "const n = parseInt(require('fs').readFileSync('/dev/stdin','utf8').trim());\nif(n <= 2){ console.log(n); }\nelse{\n    // DP: ways(n) = ways(n-1) + ways(n-2)\n    let prev = 1, curr = 2;\n    for(let i = 3; i <= n; i++)\n        [prev, curr] = [curr, prev + curr];\n    console.log(curr);\n}", timeComplexity: "O(n)", spaceComplexity: "O(1)", explanation: "Fibonacci-style DP. Destructuring swap makes it clean. O(1) space, O(n) time." }
  },
  "Coin Change (Min Coins)": {
    c: { code: "#include<stdio.h>\nint main(){\n    int n, amount;\n    scanf(\"%d%d\", &n, &amount);\n    int coins[n];\n    for(int i = 0; i < n; i++) scanf(\"%d\", &coins[i]);\n    // DP array: dp[i] = min coins to make amount i\n    int dp[amount+1];\n    for(int i = 0; i <= amount; i++) dp[i] = amount + 1; // Initialize with max\n    dp[0] = 0;  // Base case: 0 coins for amount 0\n    // Fill DP table\n    for(int i = 1; i <= amount; i++)\n        for(int j = 0; j < n; j++)\n            if(coins[j] <= i && dp[i-coins[j]] + 1 < dp[i])\n                dp[i] = dp[i-coins[j]] + 1;  // Use this coin\n    printf(\"%d\", dp[amount] > amount ? -1 : dp[amount]);\n    return 0;\n}", timeComplexity: "O(n*amount)", spaceComplexity: "O(amount)", explanation: "Bottom-up DP. dp[i] stores minimum coins needed for amount i. For each amount, try each coin — if using it gives fewer coins, update. If dp[amount] is still max, it's impossible (-1)." },
    java: { code: "import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), amount = sc.nextInt();\n        int[] coins = new int[n];\n        for(int i = 0; i < n; i++) coins[i] = sc.nextInt();\n        // dp[i] = min coins for amount i\n        int[] dp = new int[amount+1];\n        Arrays.fill(dp, amount+1);  // Max value\n        dp[0] = 0;  // Base case\n        // Fill DP\n        for(int i = 1; i <= amount; i++)\n            for(int c : coins)\n                if(c <= i) dp[i] = Math.min(dp[i], dp[i-c] + 1);\n        System.out.println(dp[amount] > amount ? -1 : dp[amount]);\n    }\n}", timeComplexity: "O(n*amount)", spaceComplexity: "O(amount)", explanation: "Classic coin change DP. Build solution bottom-up. dp[i] = min coins for amount i. Try each coin denomination and pick the minimum." },
    python: { code: "n, amount = map(int, input().split())\ncoins = list(map(int, input().split()))\n# dp[i] = minimum coins to make amount i\ndp = [amount + 1] * (amount + 1)  # Initialize with max\ndp[0] = 0  # Base case: 0 coins for amount 0\n# Fill DP table\nfor i in range(1, amount + 1):\n    for c in coins:\n        if c <= i:\n            dp[i] = min(dp[i], dp[i-c] + 1)  # Try using coin c\nprint(-1 if dp[amount] > amount else dp[amount])", timeComplexity: "O(n*amount)", spaceComplexity: "O(amount)", explanation: "DP approach: for each amount from 1 to target, try all coins. dp[i-coin]+1 means using one more coin of this denomination. Take minimum across all coins." },
    javascript: { code: "const lines = require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\nconst [n, amount] = lines[0].split(' ').map(Number);\nconst coins = lines[1].split(' ').map(Number);\n// dp[i] = min coins for amount i\nconst dp = Array(amount+1).fill(amount+1);\ndp[0] = 0;  // Base case\n// Fill DP\nfor(let i = 1; i <= amount; i++)\n    for(const c of coins)\n        if(c <= i) dp[i] = Math.min(dp[i], dp[i-c] + 1);\nconsole.log(dp[amount] > amount ? -1 : dp[amount]);", timeComplexity: "O(n*amount)", spaceComplexity: "O(amount)", explanation: "Bottom-up DP. Array dp where dp[i] = minimum coins to make amount i. -1 if impossible." }
  },
  "Longest Increasing Subsequence": {
    c: { code: "#include<stdio.h>\nint main(){\n    int n;\n    scanf(\"%d\", &n);\n    int arr[n], dp[n];\n    // Read array and initialize dp\n    for(int i = 0; i < n; i++){\n        scanf(\"%d\", &arr[i]);\n        dp[i] = 1;  // Each element is LIS of length 1\n    }\n    int ans = 1;\n    // For each element, find longest increasing subsequence ending here\n    for(int i = 1; i < n; i++){\n        for(int j = 0; j < i; j++)\n            if(arr[j] < arr[i] && dp[j] + 1 > dp[i])\n                dp[i] = dp[j] + 1;  // Extend subsequence\n        if(dp[i] > ans) ans = dp[i];  // Update global max\n    }\n    printf(\"%d\", ans);\n    return 0;\n}", timeComplexity: "O(n²)", spaceComplexity: "O(n)", explanation: "DP approach: dp[i] = length of LIS ending at index i. For each element, check all previous elements — if smaller, we can extend that subsequence. Answer is max of all dp values." },
    java: { code: "import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n], dp = new int[n];\n        Arrays.fill(dp, 1);  // Each element is LIS of 1\n        for(int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        int ans = 1;\n        // Find LIS ending at each index\n        for(int i = 1; i < n; i++){\n            for(int j = 0; j < i; j++)\n                if(arr[j] < arr[i])  // Can extend\n                    dp[i] = Math.max(dp[i], dp[j] + 1);\n            ans = Math.max(ans, dp[i]);\n        }\n        System.out.println(ans);\n    }\n}", timeComplexity: "O(n²)", spaceComplexity: "O(n)", explanation: "Classic LIS with DP. For each position i, find the longest increasing subsequence that ends at i by checking all previous positions j where arr[j] < arr[i]." },
    python: { code: "n = int(input())\narr = list(map(int, input().split()))\n# dp[i] = length of LIS ending at index i\ndp = [1] * n  # Each element alone is LIS of length 1\nfor i in range(1, n):\n    for j in range(i):\n        if arr[j] < arr[i]:  # Can extend subsequence\n            dp[i] = max(dp[i], dp[j] + 1)\nprint(max(dp))  # Answer is the maximum LIS length", timeComplexity: "O(n²)", spaceComplexity: "O(n)", explanation: "DP: dp[i] = LIS length ending at i. For each element, look back at all smaller elements and extend their subsequence. O(n²) approach — O(n log n) exists but this is clearer." },
    javascript: { code: "const lines = require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\nconst arr = lines[1].split(' ').map(Number);\n// dp[i] = LIS length ending at index i\nconst dp = Array(arr.length).fill(1);\nfor(let i = 1; i < arr.length; i++)\n    for(let j = 0; j < i; j++)\n        if(arr[j] < arr[i])  // Can extend\n            dp[i] = Math.max(dp[i], dp[j] + 1);\nconsole.log(Math.max(...dp));  // Global maximum", timeComplexity: "O(n²)", spaceComplexity: "O(n)", explanation: "O(n²) DP for LIS. Each dp[i] stores longest increasing subsequence ending at position i. Spread to find max." }
  },
};

main()
  .catch((e) => { console.error("❌ Failed:", e); process.exit(1); })
  .finally(() => prisma.$disconnect());
